### PR TITLE
fixed snr calculation

### PR DESCRIPTION
**Pull request by yezhangyinge**
I try this code but found that the SNR which is not calculated correctly. So I fixed it like this.

### CODE REVIEW

**Comment by egrinstein** [comment]
Hi @yezhangyinge, thank you very much for your work!

Could you describe a little bit why it was not working and what you did to change it?

Thanks!

**Comment by yezhangyinge** [comment]
When calculating the SNR, we use the formula:
$SNR = 10log_{10}(\frac{ac\\_ pow}{ac\\_ pow\\_ noise\\_ now}). $
Therefore, the code:
```
np.sqrt(
    ac_pow / 10 ** (acoustic_scene["SNR"] / 10)
 )
```
only calculates the desired `ac_pow_noise_now`. However, it does not account for the **original** `ac_pow_noise` of the interfering signals, resulting in an incorrect computation of the SNR scaler.

**Comment by yezhangyinge** [comment]
> Hi @yezhangyinge, thank you very much for your work!
> 
> Could you describe a little bit why it was not working and what you did to change it?
> 
> Thanks!

May I ask if my understanding is correct? Or perhaps I didn't explain clearly enough?

**Comment by egrinstein** [comment]
Hi @yezhangyinge,

Sorry for the delay, I started a new job this week so I've been really busy.
Your explanation makes sense, so I will accept the PR.

Thanks again,

Eric

**Pull request merged**
